# Generated by Django 3.2 on 2024-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('pendiente_alta', models.BooleanField(default=True, verbose_name='Pendiente de alta')),
                ('email_baja', models.BooleanField(default=False, verbose_name='Pendiente de baja')),
                ('token', models.CharField(blank=True, max_length=10, null=True, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'suscriptor',
                'verbose_name_plural': 'suscriptores',
                'ordering': ['-created'],
            },
        ),
    ]
