# Generated by Django 3.2 on 2024-03-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('image', models.ImageField(upload_to='home', verbose_name='Imagen')),
                ('pagina', models.CharField(choices=[('1', 'home'), ('2', 'faq'), ('3', 'entradas'), ('4', 'servicios'), ('5', 'contacto')], default='1', max_length=1, verbose_name='Página')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('button', models.CharField(blank=True, max_length=200, null=True, verbose_name='Botón')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'fondo',
                'verbose_name_plural': 'fondos',
                'ordering': ['-created'],
            },
        ),
    ]
