# Generated by Django 3.2 on 2024-03-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_infosection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosection',
            name='orden',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
