# Generated by Django 3.2 on 2024-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_infosection_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('1', 'servicios'), ('2', 'sobre nosotros'), ('3', 'preguntas frecuentes'), ('4', 'blog'), ('5', 'contacto')], max_length=1, verbose_name='Código')),
                ('encabezado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Encabezado')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='infohome',
            options={'ordering': ['-created'], 'verbose_name': 'información general', 'verbose_name_plural': 'información general'},
        ),
    ]
