# Generated by Django 3.2 on 2024-04-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_infosection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosection',
            name='section',
            field=models.CharField(choices=[('1', 'sobre mi'), ('2', 'faq'), ('3', 'entradas'), ('4', 'servicios'), ('5', 'newsletter'), ('6', 'contacto')], max_length=1, verbose_name='Sección'),
        ),
    ]
