# Generated by Django 3.2 on 2024-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_infosection_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohome',
            name='phone',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='whatsapp'),
        ),
    ]
