# Generated by Django 3.2 on 2024-04-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_infohome_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='infohome',
            name='whatsapp',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='whatsapp'),
        ),
        migrations.AlterField(
            model_name='infohome',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Teléfono'),
        ),
    ]
