# Generated by Django 3.2 on 2024-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20240407_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infohome',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='whatsapp'),
        ),
    ]
