# Generated by Django 3.2 on 2024-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_infohome_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='infohome',
            name='textoWhatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto de whatsapp'),
        ),
    ]
