# Generated by Django 3.2 on 2024-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Usar una clase de Fontawesome, consultar los iconos en https://fontawesome.com/search?m=free&o=r', max_length=200, null=True, verbose_name='Icono')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Imagen')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('showHome', models.BooleanField(default=True, verbose_name='Mostrar en Home')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['-created'],
            },
        ),
    ]
