# Generated by Django 3.2 on 2024-03-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Usar una clase de Fontawesome, consultar los iconos en https://fontawesome.com/search?m=free&o=r, icon que se verá en la home', max_length=200, null=True, verbose_name='Icono'),
        ),
    ]
