# Generated by Django 3.2 on 2024-03-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='text', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
