# Generated by Django 3.2 on 2024-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('showHome', models.BooleanField(default=True, verbose_name='Mostrar en Home')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'pregunta frecuente',
                'verbose_name_plural': 'preguntas frecuentes',
                'ordering': ['-created'],
            },
        ),
    ]
